### ISSUE TITLE
stac_catalog and others

### ISSUE THREAD

**Issue by jaimebayes** [intake/intake-stac#115]
Hi, 

I have installed intake version 0.6.4, but when I run this line, it did not show what I should see, as you can check it here.

`#` You should see 'stac_catalog, stac_collection, stac_item, and stac_item_collection' if intake-stac is installed
`list(intake.registry)`
['yaml_file_cat', 'yaml_files_cat', 'alias', 'catalog', 'csv', 'intake_remote', 'ndzarr', 'numpy', 'textfiles', 'zarr_cat']

I need to use open_stac_catalog but it does not exist, the code generate this couple of errors:
`cat = intake.open_stac_catalog(url)`
KeyError: 'open_stac_catalog'
AttributeError: open_stac_catalog

Any advice to fix it? 

Thanks in advance, JL

**Comment by edwardchalstrey1** [comment]
This still seems to be an issue in `0.6.5` 

@jaimebayes did you have any luck opening a stac catalog with intake?

The docs suggest this should be possible: https://intake-stac.readthedocs.io/en/latest/tutorial.html
