### ISSUE TITLE
0.4 release

### ISSUE THREAD

**Issue by jhamman** [intake/intake-stac#136]
It's been quite a while since we made a release here. Can we make 0.4 now? I think the pystac refactor has been sitting on `main` for a while and is yet to find a release. 

Before we do make a release, we do need to sort out the failing tests in #135. 

cc @scottyhq

xref: https://github.com/conda-forge/intake-stac-feedstock/issues/7

**Comment by scottyhq** [comment]
> It's been quite a while since we made a release here. Can we make 0.4 now? I think the pystac refactor has been sitting on main for a while and is yet to find a release. 

Agreed. I hadn't realized there was never a 0.4 release!

**Comment by scottyhq** [comment]
Closed by #135
