### ISSUE TITLE
thoughts about/links with sat-api-browser

### ISSUE THREAD

**Issue by martindurant** [intake/intake-stac#18]
I have not seen a demonstration, but fair amount of work apparently happening:
https://github.com/developmentseed/sat-api-browser

**Comment by matthewhanson** [comment]
This was just opened yesterday during the STAC sprint, and we talked about features and requirements. Some work is going to continue on this over the week and we'll see where it is on Friday.  Can probably give a demon at Pangeo meeting in a couple weeks.

**Comment by jsignell** [comment]
I think this can probably be closed. But maybe the current version is that there could be an integration with stac_ipyleaflet.
