### ISSUE TITLE
Intake GUI browser + predefined plots

### ISSUE THREAD

**Issue by scottyhq** [intake/intake-stac#34]
One really powerful feature would be to use the built-in intake GUI to browse the catalog and create plots (maybe the lowest-res overview image for each band?). But currently there are no pre-defined plots declared.
 
When running the following code and selecting a band under "Sources" a user sees "No predefined plots found - declare these in the catalog"

```python
# `results` come from satsearch
catalog = intake.open_stac_item_collection(results.items())
intake.gui.add(catalog)
intake.gui
```

You can run the code-block above with this example notebook:
https://github.com/pangeo-data/pangeo-tutorial/blob/agu2019/notebooks/amazon-web-services/landsat8.ipynb

**Comment by jhamman** [comment]
@scottyhq - what plots would be good defaults. I think we would basically need a mapping from the assets type (e.g. `image/x.geotiff`) to a plot. I suppose this mapping would be similar to the drivers mapping we already have: 

https://github.com/pangeo-data/intake-stac/blob/d2c3f01b2e9931da7b1d87aaa67c7e0c107c5fc7/intake_stac/catalog.py#L325-L335

**Comment by scottyhq** [comment]
The following modification to `catalog.py` exposes a plot option, but I think we will also have to change some pieces of intake-xarray to get this to load properly.

```
class StacEntry(LocalCatalogEntry):
    """
    A class representing a STAC catalog Entry
    """

    def __init__(self, key, item, stacked=False):
        """
        Construct an Intake catalog Entry from a STAC catalog Entry.
        """
        driver = self._get_driver(item)
        # test adding RGB plot to metadata
        if item['type'] == 'image/jpeg':
            item['plots'] = dict(rgb=dict(kind='rgb', frame_width=400))
```

<img width="795" alt="Screenshot 2019-12-16 15 38 53" src="https://user-images.githubusercontent.com/3924836/70952118-2fb74580-201a-11ea-990b-18fd325fa2bc.png">


```python
import xarray as xr
import hvplot.xarray
da = xr.open_rasterio(url)
da.hvplot.rgb(frame_width=400)
```

<img width="494" alt="Screenshot 2019-12-16 15 38 20" src="https://user-images.githubusercontent.com/3924836/70952125-347bf980-201a-11ea-9edd-a482761be394.png">

**Comment by scottyhq** [comment]
Just adding one more test, that suggests the above is an issue with intake-xarray loading the multiband RGB image intake calling hvplot(kind=rgb). Adding a plot with kind=image works as expected for a single band image:

```
        if item['type'] == 'image/x.geotiff':
            item['plots'] = dict(image=dict(kind='image', data_aspect=True, frame_width=500, datashade=True))
```


<img width="766" alt="Screenshot 2019-12-16 16 15 44" src="https://user-images.githubusercontent.com/3924836/70953903-ecf86c00-201f-11ea-8f2a-a0e96e7c5fa3.png">

**Comment by philippjfr** [comment]
You should generally be able to find error messages in the browser console. Should I still be looking at this notebook: https://github.com/pangeo-data/pangeo-tutorial/blob/agu2019/notebooks/amazon-web-services/landsat8.ipynb ?

**Comment by scottyhq** [comment]
Hi @philippjfr - thanks for looking into it. Yes, you can launch an interactive notebook with `aws specific content` button here: https://github.com/pangeo-data/pangeo-tutorial. Then edit `/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_stac/catalog.py` with the above code blocks to enable the plots. I'll check out the browser console in the future.
