### ISSUE TITLE
[question] transfer intake-stac to Intake GitHub organization?

### ISSUE THREAD

**Issue by jhamman** [intake/intake-stac#47]
I've been wondering for a while if it makes sense for this repo to live in the pangeo-data org, or if it would be better to have it elsewhere. It may make sense to put this project with the Intake Org (@martindurant), or if that doesn't fly, perhaps closer to other STAC tools.

In my mind, the goals of a potential transfer would be to increase the package's visibility and encourage outside contributions. 

Pinging a few folks that have participated in the project to date. @scottyhq, @matthewhanson, @andersy005, @jsignell, and @martindurant.

**Comment by martindurant** [comment]
No objection from me, of course, but I'd be surprised if the move would do much for discoverability.

On June 20, 2020 1:29:57 AM EDT, Joe Hamman <notifications@github.com> wrote:
>I've been wondering for a while if it makes sense for this repo to live
>in the pangeo-data org, or if it would be better to have it elsewhere.
>It may make sense to put this project with the Intake Org
>(@martindurant), or if that doesn't fly, perhaps closer to other STAC
>tools.
>
>In my mind, the goals of a potential transfer would be to increase the
>package's visibility and encourage outside contributions. 
>
>Pinging a few folks that have participated in the project to date.
>@scottyhq, @matthewhanson, @andersy005, @jsignell, and @martindurant. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pangeo-data/intake-stac/issues/47

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jsignell** [comment]
Intake org makes the most sense I imagine.

**Comment by andersy005** [comment]
No objection from me either. 👍 for moving it to intake org

**Comment by martindurant** [comment]
To move would require one person with admin rights to the repo and a member of intake org?
Let me know if you think you have enough votes.

**Comment by scottyhq** [comment]
Intake org sounds good to me as well!

**Comment by matthewhanson** [comment]
Sounds good, [stac-utils](https://github.com/stac-utils) is also an option but I think the Intake org makes more sense.

**Comment by jhamman** [comment]
Let's do it. Will add @martindurant as an admin here.

**Comment by martindurant** [comment]
Done. Please check that owners still have the permissions they expect.

**Comment by jhamman** [comment]
@martindurant - I don't seem to have any owner/admin rights here (not sure about others).

**Comment by martindurant** [comment]
I explicitly added you. Some people seem to have made it automatically across.

**Comment by jhamman** [comment]
Thanks @martindurant. Going to close this now.
