### ISSUE TITLE
Update tutorial with current catalogs

### ISSUE THREAD

**Issue by jhamman** [intake/intake-stac#57]
The documentation build is broken right now because the example STAC catalogs we are using in the tutorial are stale. It would be great if someone could update the tutorial with a new set of catalogs.

**Comment by scottyhq** [comment]
closed by #52

**Comment by jhamman** [comment]
I think this is still a thing: https://readthedocs.org/projects/intake-stac/builds/11729922/

**Comment by scottyhq** [comment]
closed by #61
