### ISSUE TITLE
How to deal with STAC assets that don't declare 'type'

### ISSUE THREAD

**Issue by scottyhq** [intake/intake-stac#59]
intake-stac currently assumes that every asset has an associated type (e.g. 'image/png'). 

https://github.com/intake/intake-stac/blob/f4e636dcab3b0151a1d1e47e5c64608ab609cec3/intake_stac/catalog.py#L403-L406

Apparently STAC assets are not required to list a type. For example, I was just trying to work with this one which has:
```
  "assets": {
    "data": {
      "href": "https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-087-tops-20141023_20141011-154036-33520N_31618N-PP-b56c-v2_0_2.nc"
    },
```
https://cmr.earthdata.nasa.gov/cmr-stac/ASF/collections/C1595422627-ASF/items/G1635991338-ASF

Has to do with compatibility wtih https://cmr.earthdata.nasa.gov/cmr-stac. Any ideas of best approach for these cases @jhamman  @matthewhanson ?

**Comment by scottyhq** [comment]
It would be nice if we could do item['data'].set_driver('netcdf'). But just simply reading into item['data'] raises 
```pytb
ValueError: No plugins loaded for this entry: null
A listing of installable plugins can be found at https://intake.readthedocs.io/en/latest/plugin-directory.html .
```

@martindurant - perhaps you could advise on possible approaches for 1) modifying the driver for a single catalog source, and 2) modifying the driver for all sources if not specified in a catalog?

**Comment by martindurant** [comment]
I think the driver can be accessed as `item._entries['data']._driver` (perhaps no latter underscore).
As currently implemented, the driver field cannot be a "user parameter" - that concept only relates to the set of arguments for instantiating the driver. While you can list multiple drivers for a given entry (which will be tried in order), you cannot right now morph one source instance into another kind of instance. Such code would live in `intake.source.base.DataSource.configure_new` and reference `self._entry`.

**Comment by martindurant** [comment]
So its `._driver` for the input, and `._plugin` for the found class(es)
