### ISSUE TITLE
Catalog 'NoneType' object is not callable

### ISSUE THREAD

**Issue by goriliukasbuxton** [intake/intake-stac#69]
running thru the seach example:
aws-earth-search.ipynb
and I am running into errors:
![image](https://user-images.githubusercontent.com/8904086/102792269-46535380-4376-11eb-9d29-a6ccf08c50da.png)

**Comment by andersy005** [comment]
Thank you for opening this issue, @goriliukasbuxton! The error suggests that intake-stac is not installed in your environment. Can you confirm that `intake-stac` is installed in your Python environment by running 

```bash
conda list intake-stac
```

Or 

```bash
pip show intake-stac
```
?

**Comment by andersy005** [comment]
Also, what's the output of 

```python
print(intake.registry)
```

?

**Comment by goriliukasbuxton** [comment]
ok, good catch! got resolved, thank you
