### ISSUE TITLE
KeyError: 'open_stac_item_collection'

### ISSUE THREAD

**Issue by NiklasJordan** [intake/intake-stac#80]
I downloaded the AWS Earth search notebook from the examples and whithout chaning anything. Just run the cells...

But I've got everytime the following error and don't know why:
![Screenshot 2021-04-09 at 13 30 41](https://user-images.githubusercontent.com/715033/114173690-d6be9f80-9937-11eb-91d4-67428ef5854f.png)

**Comment by kadirsahbaz** [comment]
Then, you can use `intake_stac.catalog.StacItemCollection` instead of `intake.open_stac_item_collection`. 

Relevant question in GIS SE: [Intake-STAC: KeyError: 'open_stac_item_collection'](https://gis.stackexchange.com/q/393422/29431)
